// SearchBar Molecule - Generated by T-C5.13
// Composed of: Input + Icon
// Last Updated: 2026-02-03

import React, { useState, useCallback } from 'react';
import { Input } from '@components/atoms/Input';
import { Icon } from '@components/atoms/Icon';
import './SearchBar.css';

export interface SearchBarProps {
  /** Value */
  value: string;
  /** On change handler */
  onChange: (value: string) => void;
  /** Placeholder */
  placeholder?: string;
  /** Size */
  size?: 'sm' | 'md' | 'lg';
  /** Disabled */
  disabled?: boolean;
  /** Auto focus */
  autoFocus?: boolean;
  /** On search submit */
  onSearch?: (value: string) => void;
  /** Show clear button */
  showClear?: boolean;
  /** Custom class */
  className?: string;
}

export const SearchBar: React.FC<SearchBarProps> = ({
  value,
  onChange,
  placeholder = '搜索...',
  size = 'md',
  disabled = false,
  autoFocus = false,
  onSearch,
  showClear = true,
  className = '',
}) => {
  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      onChange(e.target.value);
    },
    [onChange]
  );

  const handleClear = useCallback(() => {
    onChange('');
  }, [onChange]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter' && onSearch) {
        onSearch(value);
      }
    },
    [value, onSearch]
  );

  const handleSubmit = useCallback(() => {
    if (onSearch) {
      onSearch(value);
    }
  }, [value, onSearch]);

  return (
    <div className={['search--bar', `search-bar-${size}`, className].join(' ')}>
      <Input
        value={value}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        size={size}
        disabled={disabled}
        autoFocus={autoFocus}
        leftIcon={<Icon name="search" size="sm" />}
        rightIcon={
          showClear && value ? (
            <Icon name="close" size="sm" onClick={handleClear} className="search--bar-clear" />
          ) : null
        }
      />
      {onSearch && (
        <button
          className="search--bar-submit"
          onClick={handleSubmit}
          disabled={disabled || !value}
          aria-label="搜索"
        >
          <Icon name="search" size="sm" />
        </button>
      )}
    </div>
  );
};

// Search Bar with Suggestions Dropdown
export interface SearchSuggestion {
  id: string;
  label: string;
  type?: string;
}

export const SearchBarWithSuggestions: React.FC<{
  value: string;
  onChange: (value: string) => void;
  suggestions: SearchSuggestion[];
  onSelect: (suggestion: SearchSuggestion) => void;
  placeholder?: string;
}> = ({ value, onChange, suggestions, onSelect, placeholder = '搜索...' }) => {
  const [showSuggestions, setShowSuggestions] = useState(false);

  const handleSelect = (suggestion: SearchSuggestion) => {
    onSelect(suggestion);
    setShowSuggestions(false);
  };

  const filteredSuggestions = suggestions.filter((s) =>
    s.label.toLowerCase().includes(value.toLowerCase())
  );

  return (
    <div className="search--bar-with-suggestions">
      <SearchBar
        value={value}
        onChange={(v) => {
          onChange(v);
          setShowSuggestions(true);
        }}
        placeholder={placeholder}
        showClear={true}
      />
      {showSuggestions && value && filteredSuggestions.length > 0 && (
        <div className="search--suggestions-dropdown">
          {filteredSuggestions.map((s) => (
            <div key={s.id} className="search--suggestion-item" onClick={() => handleSelect(s)}>
              <Icon name="search" size="xs" />
              <span>{s.label}</span>
              {s.type && <span className="search--suggestion-type">{s.type}</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default SearchBar;
