// Button Atom - Generated by T-C5.5
// Uses Design System Tokens
// STRICT BEM Naming: Block--Element--Modifier
// Last Updated: 2026-02-06

import React from 'react';
import './Button.css';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  /** Button content */
  children: React.ReactNode;
  /** Visual variant */
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
  /** Size */
  size?: 'sm' | 'md' | 'lg';
  /** Click handler */
  onClick?: () => void;
  /** Disabled state */
  disabled?: boolean;
  /** Full width */
  fullWidth?: boolean;
  /** Loading state */
  loading?: boolean;
}

// BEM: Block--Modifier
const sizeClasses = {
  sm: 'btn--sm',
  md: 'btn--md',
  lg: 'btn--lg',
};

const variantClasses = {
  primary: 'btn--primary',
  secondary: 'btn--secondary',
  ghost: 'btn--ghost',
  danger: 'btn--danger',
};

export const Button: React.FC<ButtonProps> = ({
  children,
  variant = 'primary',
  size = 'md',
  onClick,
  disabled = false,
  fullWidth = false,
  loading = false,
  type = 'button',
}) => {
  return (
    <button
      type={type}
      className={[
        'btn',
        variantClasses[variant],
        sizeClasses[size],
        fullWidth ? 'btn--full' : '',
        loading ? 'btn--loading' : '',
      ].join(' ')}
      onClick={onClick}
      disabled={disabled || loading}
    >
      {loading && <span className="btn__spinner" />}
      <span className={loading ? 'btn__text--hidden' : ''}>{children}</span>
    </button>
  );
};

export default Button;
