// Card Atom - Generated by T-C5.8
// Uses Design System Tokens
// Last Updated: 2026-02-03

import React from 'react';
import './Card.css';

export interface CardProps {
  /** Card content */
  children: React.ReactNode;
  /** Optional title */
  title?: string;
  /** Padding size */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /** Hover effect */
  hoverable?: boolean;
  /** Click handler */
  onClick?: () => void;
  /** Card elevation */
  elevation?: 'none' | 'low' | 'medium' | 'high';
  /** Full width */
  fullWidth?: boolean;
  /** Additional CSS class */
  className?: string;
}

const paddingClasses = {
  none: 'card--padding-none',
  sm: 'card--padding-sm',
  md: 'card--padding-md',
  lg: 'card--padding-lg',
};

const elevationClasses = {
  none: 'card--elevation-none',
  low: 'card--elevation-low',
  medium: 'card--elevation-medium',
  high: 'card--elevation-high',
};

export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  (
    {
      children,
      title,
      padding = 'md',
      hoverable = false,
      onClick,
      elevation = 'low',
      fullWidth = false,
      className: propClassName = '',
    },
    ref
  ) => {
    const className = [
      'card',
      paddingClasses[padding],
      elevationClasses[elevation],
      hoverable ? 'card--hoverable' : '',
      fullWidth ? 'card--full-width' : '',
      onClick ? 'card--clickable' : '',
      propClassName,
    ]
      .filter(Boolean)
      .join(' ');

    if (onClick) {
      return (
        <button className={className} onClick={onClick}>
          {title && <CardTitle>{title}</CardTitle>}
          {children}
        </button>
      );
    }

    return (
      <div className={className} ref={ref}>
        {title && <CardTitle>{title}</CardTitle>}
        {children}
      </div>
    );
  }
);

// Card Title subcomponent
export interface CardTitleProps {
  children: React.ReactNode;
  className?: string;
}

export const CardTitle: React.FC<CardTitleProps> = ({ children, className = '' }) => {
  const fullClassName = ['card--title', className].filter(Boolean).join(' ');
  return <h3 className={fullClassName}>{children}</h3>;
};

// Card Content subcomponent
export interface CardContentProps {
  children: React.ReactNode;
  className?: string;
  padding?: 'none' | 'sm' | 'md' | 'lg';
}

export const CardContent: React.FC<CardContentProps> = ({
  children,
  className = '',
  padding = 'md',
}) => {
  const fullClassName = ['card--content', paddingClasses[padding], className]
    .filter(Boolean)
    .join(' ');
  return <div className={fullClassName}>{children}</div>;
};

// Card Footer subcomponent
export interface CardFooterProps {
  children: React.ReactNode;
  className?: string;
}

export const CardFooter: React.FC<CardFooterProps> = ({ children, className = '' }) => {
  const fullClassName = ['card--footer', className].filter(Boolean).join(' ');
  return <div className={fullClassName}>{children}</div>;
};

export default Card;
