// Input Atom - Generated by T-C5.9
// Uses Design System Tokens
// Last Updated: 2026-02-03

import React, { forwardRef } from 'react';
import './Input.css';

export interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {
  /** Label */
  label?: string;
  /** Error message */
  error?: string;
  /** Helper text */
  helper?: string;
  /** Left icon */
  leftIcon?: React.ReactNode;
  /** Right icon */
  rightIcon?: React.ReactNode;
  /** Size */
  size?: 'sm' | 'md' | 'lg';
  /** Full width */
  fullWidth?: boolean;
}

const sizeClasses = {
  sm: 'input--sm',
  md: 'input--md',
  lg: 'input--lg',
};

export const Input = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      label,
      error,
      helper,
      leftIcon,
      rightIcon,
      size = 'md',
      fullWidth = false,
      className = '',
      ...props
    },
    ref
  ) => {
    const inputWrapperClass = [
      'input--wrapper',
      sizeClasses[size],
      fullWidth ? 'input--full-width' : '',
      props.disabled ? 'input--disabled' : '',
      error ? 'input--error' : '',
      className,
    ].join(' ');

    return (
      <div className="input--container">
        {label && <label className="input--label">{label}</label>}

        <div className={inputWrapperClass}>
          {leftIcon && <span className="input--icon input-icon-left">{leftIcon}</span>}

          <input ref={ref} className="input" {...props} />

          {rightIcon && <span className="input--icon input-icon-right">{rightIcon}</span>}
        </div>

        {(error || helper) && (
          <span className={`input-helper ${error ? 'input--helper-error' : ''}`}>
            {error || helper}
          </span>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';

// Textarea variant
export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  label?: string;
  error?: string;
  helper?: string;
  fullWidth?: boolean;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ label, error, helper, fullWidth = false, className = '', ...props }, ref) => {
    const textareaClass = [
      'textarea',
      fullWidth ? 'textarea-full-width' : '',
      error ? 'textarea-error' : '',
      className,
    ].join(' ');

    return (
      <div className="textarea-container">
        {label && <label className="textarea-label">{label}</label>}
        <textarea ref={ref} className={textareaClass} {...props} />
        {(error || helper) && (
          <span className={`textarea-helper ${error ? 'textarea-helper-error' : ''}`}>
            {error || helper}
          </span>
        )}
      </div>
    );
  }
);

Textarea.displayName = 'Textarea';

export default Input;
