// Design Tokens - Animations
// Generated by T-C5.x
// Last Updated: 2026-02-04

// Transition Durations
export const transitionDuration = {
  fast: '150ms',
  DEFAULT: '200ms',
  normal: '300ms',
  slow: '500ms',
  slower: '700ms',
  slowest: '1000ms',
} as const;

// Transition Easings
export const transitionEasing = {
  DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
  linear: 'linear(0, 1)',
  'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
  'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
  'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
  'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
} as const;

// Animation Keyframes
export const keyframes = {
  fadeIn: {
    from: { opacity: '0' },
    to: { opacity: '1' },
  },
  fadeOut: {
    from: { opacity: '1' },
    to: { opacity: '0' },
  },
  slideInUp: {
    from: { transform: 'translateY(10px)', opacity: '0' },
    to: { transform: 'translateY(0)', opacity: '1' },
  },
  slideInDown: {
    from: { transform: 'translateY(-10px)', opacity: '0' },
    to: { transform: 'translateY(0)', opacity: '1' },
  },
  scaleIn: {
    from: { transform: 'scale(0.95)', opacity: '0' },
    to: { transform: 'scale(1)', opacity: '1' },
  },
  pulse: {
    '0%, 100%': { opacity: '1' },
    '50%': { opacity: '0.5' },
  },
  spin: {
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
  },
  bounce: {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-25%)' },
  },
} as const;

// Animation Classes
export const animations = {
  fadeIn: `animation: fadeIn ${transitionDuration.normal} ${transitionEasing.DEFAULT}`,
  fadeOut: `animation: fadeOut ${transitionDuration.normal} ${transitionEasing.DEFAULT}`,
  slideInUp: `animation: slideInUp ${transitionDuration.normal} ${transitionEasing.DEFAULT}`,
  slideInDown: `animation: slideInDown ${transitionDuration.normal} ${transitionEasing.DEFAULT}`,
  scaleIn: `animation: scaleIn ${transitionDuration.fast} ${transitionEasing.DEFAULT}`,
  pulse: `animation: pulse 2s ${transitionEasing.DEFAULT} infinite`,
  spin: `animation: spin 1s ${transitionEasing.linear} infinite`,
  bounce: `animation: bounce 1s ${transitionEasing.DEFAULT} infinite`,
} as const;

// Transition Classes
export const transitions = {
  DEFAULT: `transition: all ${transitionDuration.DEFAULT} ${transitionEasing.DEFAULT}`,
  colors: `transition: color ${transitionDuration.fast} ${transitionEasing.DEFAULT}, background-color ${transitionDuration.fast} ${transitionEasing.DEFAULT}, border-color ${transitionDuration.fast} ${transitionEasing.DEFAULT}`,
  opacity: `transition: opacity ${transitionDuration.fast} ${transitionEasing.DEFAULT}`,
  transform: `transition: transform ${transitionDuration.normal} ${transitionEasing.DEFAULT}`,
} as const;

export const animationTokens = {
  transitionDuration,
  transitionEasing,
  keyframes,
  animations,
  transitions,
} as const;

export type AnimationTokens = typeof animationTokens;
