// Design Tokens - Colors
// Generated by T-C5.2
// Last Updated: 2026-02-03

// Semantic Colors
export const colors = {
  primary: {
    DEFAULT: '#0f1419',
    hover: '#1a1f26',
    active: '#242b33',
    muted: 'rgba(15, 20, 25, 0.1)',
  },
  secondary: {
    DEFAULT: '#1a1f26',
    hover: '#242b33',
    active: '#2d3640',
    muted: 'rgba(26, 31, 38, 0.1)',
  },
  accent: {
    DEFAULT: '#00d4aa',
    hover: '#00b894',
    active: '#00997a',
    muted: 'rgba(0, 212, 170, 0.1)',
  },
} as const;

// Functional Colors
export const functionalColors = {
  success: {
    DEFAULT: '#4caf50',
    light: '#81c784',
    dark: '#388e3c',
  },
  warning: {
    DEFAULT: '#ff9800',
    light: '#ffb74d',
    dark: '#f57c00',
  },
  danger: {
    DEFAULT: '#f44336',
    light: '#e57373',
    dark: '#d32f2f',
  },
  info: {
    DEFAULT: '#2196f3',
    light: '#64b5f6',
    dark: '#1976d2',
  },
} as const;

// Neutrals (Gray Scale)
export const neutrals = {
  gray: {
    50: '#fafafa',
    100: '#f5f5f5',
    200: '#eeeeee',
    300: '#e0e0e0',
    400: '#bdbdbd',
    500: '#9e9e9e',
    600: '#757575',
    700: '#616161',
    800: '#424242',
    900: '#212121',
  },
} as const;

// Background Colors
export const backgrounds = {
  default: {
    light: '#ffffff',
    dark: '#0f1419',
  },
  surface: {
    light: '#f5f5f5',
    dark: '#1a1f26',
  },
  elevated: {
    light: '#ffffff',
    dark: '#242b33',
  },
} as const;

// Text Colors
export const textColors = {
  primary: {
    light: '#212121',
    dark: '#ffffff',
  },
  secondary: {
    light: '#757575',
    dark: '#b0b0b0',
  },
  muted: {
    light: '#9e9e9e',
    dark: '#757575',
  },
  inverse: {
    light: '#ffffff',
    dark: '#0f1419',
  },
} as const;

// Border Colors
export const borderColors = {
  light: '#e0e0e0',
  dark: '#2d3640',
  focus: {
    DEFAULT: '#00d4aa',
    error: '#f44336',
  },
} as const;

// Export all tokens
export const colorTokens = {
  ...colors,
  ...functionalColors,
  ...neutrals,
  ...backgrounds,
  ...textColors,
  ...borderColors,
};

export type ColorTokens = typeof colorTokens;
