// Design System Tokens Index
// Generated by T-C5.2
// Last Updated: 2026-02-04

// Color Tokens
export * from './colors';
export type { ColorTokens } from './colors';

// Typography Tokens
export * from './typography';
export type { TypographyTokens } from './typography';

// Spacing Tokens
export * from './spacing';
export type { SpacingTokens } from './spacing';

// Additional Tokens
export * from './radius';
export type { RadiusTokens } from './radius';

export * from './shadows';
export type { ShadowTokens } from './shadows';

export * from './animations';
export type { AnimationTokens } from './animations';

// Combined tokens object for CSS custom properties
import { colorTokens } from './colors';
import { typography } from './typography';
import { spacing } from './spacing';
import { radii } from './radius';
import { shadows } from './shadows';
import { transitionDuration, transitionEasing, animations } from './animations';

export const tokens = {
  // Colors
  ...colorTokens,
  
  // Typography
  ...typography,
  
  // Spacing
  ...spacing,
  
  // Radius
  ...radii,
  
  // Shadows
  ...shadows,
  
  // Animations
  transitionDuration,
  transitionEasing,
} as const;

export type AllTokens = typeof tokens;
