// Design Tokens - Border Radius
// Generated by T-C5.x
// Last Updated: 2026-02-04

// Border Radius Scale
export const radii = {
  none: '0',
  sm: '0.125rem',    // 2px
  DEFAULT: '0.25rem', // 4px
  md: '0.375rem',    // 6px
  lg: '0.5rem',      // 8px
  xl: '0.75rem',     // 12px
  '2xl': '1rem',     // 16px
  '3xl': '1.5rem',   // 24px
  full: '9999px',    // Circle / Pill
} as const;

export type RadiusTokens = typeof radii;

// Common border radius combinations
export const borderRadius = {
  button: {
    sm: radii.sm,
    md: radii.md,
    lg: radii.lg,
    full: radii.full,
  },
  input: {
    DEFAULT: radii.md,
    sm: radii.sm,
    lg: radii.lg,
  },
  card: {
    DEFAULT: radii.lg,
    sm: radii.md,
    lg: radii.xl,
  },
  badge: {
    DEFAULT: radii.full,
    sm: radii.sm,
    md: radii.md,
  },
  avatar: {
    DEFAULT: radii.full,
    sm: radii.md,
    lg: radii['2xl'],
  },
} as const;
