// Design Tokens - Spacing
// Generated by T-C5.2
// Last Updated: 2026-02-04

// Spacing Scale (Tailwind-compatible)
export const spacing = {
  0: '0rem',        // 0px
  0.5: '0.125rem',  // 2px
  1: '0.25rem',     // 4px
  1.5: '0.375rem',  // 6px
  2: '0.5rem',      // 8px
  2.5: '0.625rem',  // 10px
  3: '0.75rem',     // 12px
  3.5: '0.875rem',  // 14px
  4: '1rem',        // 16px
  5: '1.25rem',     // 20px
  6: '1.5rem',      // 24px
  7: '1.75rem',     // 28px
  8: '2rem',        // 32px
  9: '2.25rem',     // 36px
  10: '2.5rem',     // 40px
  11: '2.75rem',    // 44px
  12: '3rem',       // 48px
  14: '3.5rem',     // 56px
  16: '4rem',       // 64px
  20: '5rem',       // 80px
  24: '6rem',       // 96px
} as const;

export type SpacingTokens = typeof spacing;

// Layout Spacing
export const layoutSpacing = {
  gutter: spacing[4],      // 16px
  container: spacing[6],   // 24px
  section: spacing[8],     // 32px
  sectionLarge: spacing[12], // 48px
} as const;

// Component Spacing
export const componentSpacing = {
  button: {
    x: spacing[4],   // 16px
    y: spacing[2],   // 8px
  },
  input: {
    x: spacing[3],   // 12px
    y: spacing[2],   // 8px
  },
  card: {
    padding: spacing[4],    // 16px
    paddingSm: spacing[3],  // 12px
    paddingLg: spacing[6],  // 24px
  },
  badge: {
    x: spacing[2],   // 8px
    y: spacing[0.5], // 2px
  },
} as const;

// Gap Spacing
export const gapSpacing = {
  xs: spacing[1],    // 4px
  sm: spacing[2],    // 8px
  md: spacing[3],    // 12px
  DEFAULT: spacing[4], // 16px
  lg: spacing[6],    // 24px
  xl: spacing[8],    // 32px
  '2xl': spacing[12], // 48px
} as const;
