// DataCard Molecule - Generated by T-C5.12
// Composed of: Card + Title + Value + Trend
// Last Updated: 2026-02-03

import React from 'react';
import { Card } from '../../atoms/Card';
import './DataCard.css';

export interface DataCardProps {
  /** Title */
  title: string;
  /** Value (string or number) */
  value: string | number;
  /** Trend direction */
  trend?: 'up' | 'down' | 'neutral';
  /** Trend value */
  trendValue?: string;
  /** Trend label */
  trendLabel?: string;
  /** Icon */
  icon?: React.ReactNode;
  /** Subtitle */
  subtitle?: string;
  /** Click handler */
  onClick?: () => void;
  /** Highlight */
  highlighted?: boolean;
}

const trendIcons = {
  up: '↑',
  down: '↓',
  neutral: '→',
};

const trendColors = {
  up: '#4caf50',
  down: '#f44336',
  neutral: '#9e9e9e',
};

export const DataCard: React.FC<DataCardProps> = ({
  title,
  value,
  trend = 'neutral',
  trendValue,
  trendLabel,
  icon,
  subtitle,
  onClick,
  highlighted = false,
}) => {
  return (
    <Card onClick={onClick} hoverable={!!onClick} elevation={highlighted ? 'medium' : 'low'}>
      <div className={['data--card', highlighted ? 'data--card-highlighted' : ''].join(' ')}>
        <div className="data--card-header">
          <span className="data--card-title">{title}</span>
          {icon && <span className="data--card-icon">{icon}</span>}
        </div>

        <div className="data--card-value">{value}</div>

        {(trendValue || subtitle) && (
          <div className="data--card-footer">
            {trendValue && (
              <span className="data--card-trend" style={{ color: trendColors[trend] }}>
                {trendIcons[trend]} {trendValue}
              </span>
            )}
            {trendLabel && <span className="data--card-trend-label">{trendLabel}</span>}
            {subtitle && <span className="data--card-subtitle">{subtitle}</span>}
          </div>
        )}
      </div>
    </Card>
  );
};

// Dashboard Grid for DataCards
export const DataCardGrid: React.FC<{
  items: Array<Omit<DataCardProps, 'children'>>;
  columns?: 2 | 3 | 4;
}> = ({ items, columns = 4 }) => {
  return (
    <div className={`data-card-grid data-card-grid-${columns}`}>
      {items.map((item, index) => (
        <DataCard key={index} {...item} />
      ))}
    </div>
  );
};

export default DataCard;
