// Design System Index - Generated by T-C5.2
// Last Updated: 2026-02-07 (设计系统集中化修复)

// Tokens
export * from './tokens';

// Components
export * from './components';

// Re-export for backward compatibility
export * from './tokens';