// Badge Atom - Generated by T-C5.7
// Uses Design System Tokens
// Last Updated: 2026-02-03

import React from 'react';
import './Badge.css';

export interface BadgeProps {
  /** Badge content */
  children: React.ReactNode;
  /** Visual variant */
  variant?: 'success' | 'warning' | 'danger' | 'info' | 'neutral' | 'secondary';
  /** Size */
  size?: 'sm' | 'md';
  /** Optional icon */
  icon?: React.ReactNode;
}

const variantClasses = {
  success: 'badge--success',
  warning: 'badge--warning',
  danger: 'badge--danger',
  info: 'badge--info',
  neutral: 'badge--neutral',
  secondary: 'badge--secondary',
};

const sizeClasses = {
  sm: 'badge--sm',
  md: 'badge--md',
};

export const Badge: React.FC<BadgeProps> = ({
  children,
  variant = 'neutral',
  size = 'md',
  icon,
}) => {
  return (
    <span className={['badge', variantClasses[variant], sizeClasses[size]].join(' ')}>
      {icon && <span className="badge--icon">{icon}</span>}
      <span className="badge--text">{children}</span>
    </span>
  );
};

// Status Badge convenience component
export const StatusBadge: React.FC<{
  status: 'online' | 'offline' | 'error' | 'warning' | 'loading';
  label?: string;
}> = ({ status, label }) => {
  const config = {
    online: { variant: 'success' as const, icon: '●' },
    offline: { variant: 'neutral' as const, icon: '○' },
    error: { variant: 'danger' as const, icon: '●' },
    warning: { variant: 'warning' as const, icon: '!' },
    loading: { variant: 'info' as const, icon: '◉' },
  };

  const { variant, icon } = config[status];

  return (
    <Badge variant={variant} size="sm">
      {icon} {label || status}
    </Badge>
  );
};

export default Badge;
