// Avatar Stories - Visual Regression Tests
// Generated by T-C5-F3
// Last Updated: 2026-02-03

import type { Meta, StoryObj } from '@storybook/react';
import { Avatar, AvatarGroup } from '../components/atoms/Avatar/Avatar';

export default {
  title: 'Atoms/Avatar',
  component: Avatar,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
} as Meta;

export const Default: StoryObj = {
  args: {
    src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    alt: 'User avatar',
    size: 'md',
    shape: 'circle',
  },
};

export const Fallback: StoryObj = {
  args: {
    fallback: 'JD',
    size: 'md',
    shape: 'circle',
  },
};

export const Square: StoryObj = {
  args: {
    src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    alt: 'User avatar',
    size: 'md',
    shape: 'square',
  },
};

export const Sizes: StoryObj = {
  render: () => (
    <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="xs" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="sm" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="md" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="lg" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="xl" />
    </div>
  ),
};

export const WithStatus: StoryObj = {
  render: () => (
    <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="md" status="online" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="md" status="offline" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="md" status="busy" />
      <Avatar src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" size="md" status="away" />
    </div>
  ),
};

export const AvatarGroup: StoryObj = {
  render: () => (
    <AvatarGroup
      avatars={[
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', alt: 'User 1' },
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Max', alt: 'User 2' },
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Anna', alt: 'User 3' },
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John', alt: 'User 4' },
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike', alt: 'User 5' },
        { src: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah', alt: 'User 6' },
      ]}
      max={5}
      size="md"
    />
  ),
};
