// ConnectionStatus Stories - Visual Regression Tests
// Generated by T-C5-F3
// Last Updated: 2026-02-03

import type { Meta, StoryObj } from '@storybook/react';
import { ConnectionStatus } from '../ConnectionStatus';

export default {
  title: 'Molecules/ConnectionStatus',
  component: ConnectionStatus,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
} as Meta;

export const Connected: StoryObj = {
  args: {
    isConnected: true,
    lastConnected: new Date(),
    serverUrl: 'http://localhost:8000',
    size: 'md',
    showTimestamp: true,
  },
};

export const Disconnected: StoryObj = {
  args: {
    isConnected: false,
    lastConnected: new Date(Date.now() - 3600000),
    serverUrl: 'http://localhost:8000',
    size: 'md',
    showTimestamp: true,
  },
};

export const Small: StoryObj = {
  args: {
    isConnected: true,
    lastConnected: new Date(),
    size: 'sm',
    showTimestamp: false,
  },
};

export const Large: StoryObj = {
  args: {
    isConnected: true,
    lastConnected: new Date(),
    size: 'lg',
    showTimestamp: true,
  },
};

export const NoTimestamp: StoryObj = {
  args: {
    isConnected: true,
    lastConnected: new Date(),
    showTimestamp: false,
  },
};
