// Dashboard Stories - Visual Regression Tests
// Generated by T-C5-F3
// Last Updated: 2026-02-03

import type { Meta, StoryObj } from '@storybook/react';
import { Dashboard } from '../components/dashboard/Dashboard';

export default {
  title: 'Organisms/Dashboard',
  component: Dashboard,
  parameters: {
    layout: 'fullscreen',
  },
  tags: ['autodocs'],
} as Meta;

export const Empty: StoryObj = {
  args: {},
};

export const WithData: StoryObj = {
  args: {},
  play: async ({ canvasElement }) => {
    // In a real scenario, this would populate the store with data
    // For visual regression testing, we can mock this in CSF3
  },
};

export const DarkMode: StoryObj = {
  args: {},
  parameters: {
    backgrounds: {
      default: 'dark',
    },
  },
};
