// DataCard Stories - Visual Regression Tests
// Generated by T-C5-F3
// Last Updated: 2026-02-03

import type { Meta, StoryObj } from '@storybook/react';
import { DataCard, DataCardGrid } from '../components/molecules/DataCard/DataCard';

export default {
  title: 'Molecules/DataCard',
  component: DataCard,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
} as Meta;

export const Default: StoryObj = {
  args: {
    title: '市场总成交额',
    value: '$1,234,567',
    trend: 'up',
    trendValue: '+2.5%',
  },
};

export const WithSubtitle: StoryObj = {
  args: {
    title: '模拟持仓净值',
    value: '$98,765',
    trend: 'down',
    trendValue: '-1.2%',
    subtitle: '日收益: -1.2%',
  },
};

export const Highlighted: StoryObj = {
  args: {
    title: '高风险警报',
    value: '3',
    trend: 'down',
    trendValue: '需要关注',
    highlighted: true,
  },
};

export const WithIcon: StoryObj = {
  args: {
    title: 'RSRS 强度',
    value: '0.85',
    trend: 'up',
    trendValue: '+0.05',
    icon: '📈',
  },
};

export const Grid: StoryObj = {
  render: () => (
    <DataCardGrid
      items={[
        { title: '总资产', value: '$1,234,567', trend: 'up', trendValue: '+2.5%' },
        { title: '持仓数量', value: '42', trend: 'neutral' },
        { title: '今日收益', value: '+$1,234', trend: 'up', trendValue: '+1.5%' },
        { title: '可用资金', value: '$50,000', trend: 'neutral' },
      ]}
      columns={4}
    />
  ),
  parameters: {
    layout: 'fullscreen',
  },
};
