// StatusIndicator Molecule - Generated by T-C5.11
// Composed of: Icon + Badge + Text
// Last Updated: 2026-02-03

import React from 'react';
import { StatusDot, StatusDotProps } from '../../atoms/StatusDot';
import './StatusIndicator.css';

export interface StatusIndicatorProps {
  /** Status state */
  status: 'online' | 'offline' | 'error' | 'warning' | 'loading';
  /** Label text */
  label: string;
  /** Size */
  size?: 'sm' | 'md' | 'lg';
  /** Show timestamp */
  timestamp?: string;
  /** Description */
  description?: string;
}

const statusVariant: Record<string, StatusDotProps['status']> = {
  online: 'connected',
  offline: 'disconnected',
  error: 'error',
  warning: 'warning',
  loading: 'loading',
};

export const StatusIndicator: React.FC<StatusIndicatorProps> = ({
  status,
  label,
  size = 'md',
  timestamp,
  description,
}) => {
  return (
    <div className={['status--indicator', `status-indicator-${size}`].join(' ')}>
      <StatusDot
        status={statusVariant[status]}
        size={size}
        pulse={status === 'online' || status === 'loading'}
      />
      <div className="status--indicator-content">
        <span className="status--indicator-label">{label}</span>
        {timestamp && <span className="status--indicator-timestamp">{timestamp}</span>}
        {description && <span className="status--indicator-description">{description}</span>}
      </div>
    </div>
  );
};

// System Status Panel - Full molecule with list
export const SystemStatusPanel: React.FC<{
  items: Array<{
    id: string;
    label: string;
    status: 'online' | 'offline' | 'error' | 'warning' | 'loading';
    timestamp?: string;
    description?: string;
  }>;
}> = ({ items }) => {
  return (
    <div className="status--panel">
      {items.map((item) => (
        <StatusIndicator
          key={item.id}
          status={item.status}
          label={item.label}
          size="sm"
          timestamp={item.timestamp}
          description={item.description}
        />
      ))}
    </div>
  );
};

export default StatusIndicator;
