// Avatar Atom - Generated by T-C5-F2
// Uses BEM Naming + CSS Variables
// Last Updated: 2026-02-03

import React, { useState } from 'react';
import './Avatar.css';

export interface AvatarProps {
  /** Image source URL */
  src?: string;
  /** Alt text for accessibility */
  alt?: string;
  /** Size */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Shape */
  shape?: 'circle' | 'square';
  /** Fallback text (initials) */
  fallback?: string;
  /** Status indicator */
  status?: 'online' | 'offline' | 'busy' | 'away';
  /** Click handler */
  onClick?: () => void;
  /** Custom class */
  className?: string;
}

const sizeMap = {
  xs: 24,
  sm: 32,
  md: 40,
  lg: 48,
  xl: 64,
};

const statusColors = {
  online: 'var(--color-success)',
  offline: 'var(--color-neutral)',
  busy: 'var(--color-danger)',
  away: 'var(--color-warning)',
};

export const Avatar: React.FC<AvatarProps> = ({
  src,
  alt = '',
  size = 'md',
  shape = 'circle',
  fallback,
  status,
  onClick,
  className = '',
}) => {
  const [imageError, setImageError] = useState(false);
  const sizePx = sizeMap[size];
  const initials = fallback || alt?.slice(0, 2).toUpperCase() || '?';

  const handleImageError = () => {
    setImageError(true);
  };

  const shapeClass = shape === 'circle' ? 'avatar--circle' : 'avatar--square';
  const clickableClass = onClick ? 'avatar--clickable' : '';

  const combinedClassName = ['avatar', shapeClass, clickableClass, className].join(' ');

  return (
    <div
      className={combinedClassName}
      style={{ '--avatar-size': `${sizePx}px` } as React.CSSProperties}
    >
      {src && !imageError ? (
        <img src={src} alt={alt} className="avatar__image" onError={handleImageError} />
      ) : (
        <span className="avatar__fallback">{initials}</span>
      )}

      {status && (
        <span
          className="avatar__status"
          style={{ '--status-color': statusColors[status] } as React.CSSProperties}
        />
      )}
    </div>
  );
};

// Avatar Group (multiple avatars stacked)
export interface AvatarGroupProps {
  avatars: Array<{
    src?: string;
    alt?: string;
    fallback?: string;
    onClick?: () => void;
  }>;
  max?: number;
  size?: 'xs' | 'sm' | 'md' | 'lg';
}

export const AvatarGroup: React.FC<AvatarGroupProps> = ({ avatars, max = 5, size = 'sm' }) => {
  const visible = avatars.slice(0, max);
  const remaining = avatars.length - max;

  return (
    <div
      className="avatar--group"
      style={{ '--avatar-size': `${sizeMap[size]}px` } as React.CSSProperties}
    >
      {visible.map((avatar, index) => (
        <Avatar key={index} {...avatar} size={size} className="avatar--group__item" />
      ))}
      {remaining > 0 && <div className="avatar--group__more">+{remaining}</div>}
    </div>
  );
};

export default Avatar;
