// StatusDot Atom - Generated by T-C5.10
// Uses Design System Tokens
// Last Updated: 2026-02-03

import React from 'react';
import './StatusDot.css';

export interface StatusDotProps {
  /** Status state */
  status: 'connected' | 'disconnected' | 'loading' | 'error' | 'warning';
  /** Size */
  size?: 'sm' | 'md' | 'lg';
  /** Label */
  label?: string;
  /** Show pulse animation */
  pulse?: boolean;
}

const statusConfig = {
  connected: { color: '#4caf50', bgColor: 'rgba(76, 175, 80, 0.2)' },
  disconnected: { color: '#9e9e9e', bgColor: 'rgba(158, 158, 158, 0.2)' },
  loading: { color: '#2196f3', bgColor: 'rgba(33, 150, 243, 0.2)' },
  error: { color: '#f44336', bgColor: 'rgba(244, 67, 54, 0.2)' },
  warning: { color: '#ff9800', bgColor: 'rgba(255, 152, 0, 0.2)' },
};

const sizeConfig = {
  sm: { dot: 8, font: '0.75rem' },
  md: { dot: 10, font: '0.875rem' },
  lg: { dot: 12, font: '1rem' },
};

export const StatusDot: React.FC<StatusDotProps> = ({
  status,
  size = 'md',
  label,
  pulse = false,
}) => {
  const { color, bgColor } = statusConfig[status];
  const { dot, font } = sizeConfig[size];
  const showLabel = label !== undefined;

  return (
    <span
      className={['status--dot', pulse ? `status-dot-pulse-${status}` : ''].join(' ')}
      style={
        {
          '--status-color': color,
          '--status-bg': bgColor,
          '--dot-size': `${dot}px`,
        } as React.CSSProperties
      }
    >
      <span
        className="status--dot-indicator"
        style={{ width: `${dot}px`, height: `${dot}px`, backgroundColor: color }}
      />
      {showLabel && (
        <span className="status--dot-label" style={{ fontSize: font }}>
          {label}
        </span>
      )}
    </span>
  );
};

// Convenience components for common use cases
export const ConnectionStatus: React.FC<{
  connected: boolean;
  label?: boolean;
}> = ({ connected, label = true }) => (
  <StatusDot
    status={connected ? 'connected' : 'disconnected'}
    label={label ? (connected ? '已连接' : '已断开') : undefined}
    pulse={connected}
  />
);

export const LoadingStatus: React.FC<{ label?: string }> = ({ label = '加载中...' }) => (
  <StatusDot status="loading" label={label} pulse />
);

export const ErrorStatus: React.FC<{ label?: string }> = ({ label = '错误' }) => (
  <StatusDot status="error" label={label} />
);

export default StatusDot;
