// FormGroup Molecule - Generated by T-C5.14
// Composed of: Label + Input + Error Message
// Last Updated: 2026-02-03

import React, { ReactNode } from 'react';
import './FormGroup.css';

export interface FormGroupProps {
  /** Label */
  label: string;
  /** Children (Input, Select, etc.) */
  children: ReactNode;
  /** Error message */
  error?: string;
  /** Helper text */
  helper?: string;
  /** Required indicator */
  required?: boolean;
  /** Layout */
  layout?: 'vertical' | 'horizontal';
  /** Full width */
  fullWidth?: boolean;
}

export const FormGroup: React.FC<FormGroupProps> = ({
  label,
  children,
  error,
  helper,
  required = false,
  layout = 'vertical',
  fullWidth = false,
}) => {
  return (
    <div
      className={[
        'form--group',
        `form-group-${layout}`,
        fullWidth ? 'form--group-full-width' : '',
        error ? 'form--group-error' : '',
      ].join(' ')}
    >
      <label className="form--group-label">
        {label}
        {required && <span className="form--group-required">*</span>}
      </label>
      <div className="form--group-content">{children}</div>
      {(error || helper) && (
        <span className={`form-group-helper ${error ? 'form--group-helper-error' : ''}`}>
          {error || helper}
        </span>
      )}
    </div>
  );
};

// Form Row (multiple form groups in one row)
export interface FormRowProps {
  children: ReactNode;
  gap?: number;
}

export const FormRow: React.FC<FormRowProps> = ({ children, gap = 16 }) => {
  return (
    <div className="form--row" style={{ gap }}>
      {children}
    </div>
  );
};

// Form Section (grouped form fields with title)
export interface FormSectionProps {
  title: string;
  children: ReactNode;
  description?: string;
}

export const FormSection: React.FC<FormSectionProps> = ({ title, children, description }) => {
  return (
    <fieldset className="form--section">
      <legend className="form--section-title">{title}</legend>
      {description && <p className="form--section-description">{description}</p>}
      <div className="form--section-content">{children}</div>
    </fieldset>
  );
};

// Checkbox Form Group
export interface CheckboxGroupProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  description?: string;
}

export const CheckboxGroup: React.FC<CheckboxGroupProps> = ({
  label,
  checked,
  onChange,
  description,
}) => {
  return (
    <label className="checkbox-group">
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="checkbox-input"
      />
      <span className="checkbox-label">{label}</span>
      {description && <span className="checkbox-description">{description}</span>}
    </label>
  );
};

export default FormGroup;
